### ISSUE TITLE
Thunderbolt System Report/ Inquiry of USB Ports fixed to All USB 3

### ISSUE THREAD

**Issue by bennydf123** [baughmann/designaire-z390-intel-i9-9900k-opencore#5] opened 2020-08-07 02:52 UTC
![Screen Shot 2020-08-07 at 12 49 27 pm](https://user-images.githubusercontent.com/69333691/89603856-52e67c00-d8ad-11ea-8b51-1d2d47680f5a.png)
Thunderbolt system not showing. Although this is not a pressing issue in the build, it would be nice to view data, to monitor audio from my PCI card. Also, wondering if the ports are all mapped to USB 3? 

*Note I'm not a programmer and am very thankful for the EFI and Opencore set up. Very effective.

**Comment by baughmann** [comment] 2020-08-07 21:21
@bennydf123 Can you confirm that your TB3 port still operates as expected, it's just not showing the data here?

I can confirm that this is an issue. My setup shows the same lack of info.

I can do some playing/digging around to see if I can get anything to show up. However, I would very much like your assistance to. First thing we need to do is research around to find some likely causes.

My first guess at the likely culprits would be either:
- Incomplete implementation of `USBPorts.kext`
    - I'm not really sure what a "complete" implementation would look like
- Something's getting messed up by `USBInjectAll.kext`
- Something is missing in one of the ACPIs

**Comment by baughmann** [comment] 2020-08-07 22:15
After trying OpenCore's [recommend USB mapping method])(https://dortania.github.io/OpenCore-Post-Install/usb/intel-mapping/intel.html) using [corpnewt's USBMap application](https://github.com/corpnewt/USBMap), I sadly failed. This was probably due to my lack of effort, I didn't really put much time into trying to build the `USBMap.kext`. The one I built for some reason disabled the USB Hub that my BT card was on despite the fact that I [thought] I selected it.

Even using `USBMap.kext` I was unable to see any info for the TB3 ports.

Further, if i *were* to have a successful USB mapping and disable `USBInjectAll.kext` we would all be suffering from the "which USB ports are enabled again?" problem. USB port maps, both in OC and in Clover, have a hard-cap of 15 ports AFAIK.

After some Googling, it looks like we're lucky that our TB3 ports even work, and that it's unlikely that we will be seeing much diagnostic info from them :(

I'm gonna label this as a `wontfix` for now, and close it in a few days unless we come across some new info.

**Comment by bennydf123** [comment] 2020-08-09 08:49
I came across someone who managed to get info on Thunderbolt using Multibeast but I'm assuming it would take quite a bit of time to reverse engineer the steps and not change the USB Map. The main thing is that my Thunderbolt is working and it is just the driver information not showing. Thanks for trying.

**Comment by baughmann** [comment] 2020-08-09 15:14
@bennydf123 If you send me the link I can try to look into it.

**Comment by bennydf123** [comment] 2020-08-10 10:03
There's this one but that was using a complete Tony Macx build (not clean).
https://www.tonymacx86.com/threads/success-gigabyte-designare-z390-thunderbolt-3-i7-9700k-amd-rx-580.267551/page-2102#post-2122559

There was another one I came across but I think that was deleted.

**Comment by baughmann** [comment] 2020-08-11 01:02
Looks like there's no existing solution for now :(

**Closed by baughmann** 2020-08-11 01:02 UTC
Labels: wontfix
