### ISSUE TITLE
iGPU not working  for TV+ and can't play Netflix on Safari

### ISSUE THREAD

**Issue by magnificent3** [baughmann/designaire-z390-intel-i9-9900k-opencore#40] opened 2021-01-15 14:41 UTC
TV+ not working when trying to play content other than trailers.
iTunes Music videos have the same issue.

 - CPU: Intel Core i7 9700
 - GPU: Radeon RX580 8GB
 - Motherboard: Asus Z390-M PRIME
 - Storage: NVME WDBlue 500GB

When disabled the iGPU it works, but sidecar and airplay won't work.

Everything else works fine.

Can you help?

**Comment by baughmann** [comment] 2021-03-10 14:35
Sorry for the super-delayed response, @magnificent3 

I *was* able to reproduce this, but since I do not use this feature and do not know a possible solution I'm not sure how to help.

After a quick Google search, it appears this is probably related to DRM, and WhateverGreen does not have a working DRM patch for Big Sur yet, [according to the docs](https://dortania.github.io/OpenCore-Post-Install/universal/drm.html).

As such, we're kinda SOL until that happens.

If you run across a working DRM patch for Big Sur, please let me know. I'm gonna label this as a wontfix and keep it open until you respond, or for a few days, whichever comes first.

**Comment by baughmann** [comment] 2021-03-10 17:19
Yeah, I don't think you can use SideCar with the iGPU enabled, to the best of my knowledge.

Unfortunately, I do not have an iPad so it's difficult for me to troubleshoot it :/

**Comment by baughmann** [comment] 2021-03-17 13:20
Closing due to lack of activity. Re-open if you need help :)

**Closed by baughmann** 2021-03-17 13:20 UTC
Labels: bug, wontfix
